# Generated by Django 5.2.9 on 2025-12-19 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'comuna',
            },
        ),
        migrations.CreateModel(
            name='control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'control',
            },
        ),
        migrations.CreateModel(
            name='especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'especie',
            },
        ),
        migrations.CreateModel(
            name='estadocita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'estadocita',
            },
        ),
        migrations.CreateModel(
            name='estadocliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'estadocliente',
            },
        ),
        migrations.CreateModel(
            name='prestacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'prestacion',
            },
        ),
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=13, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=60)),
                ('direccion', models.CharField(max_length=80)),
                ('plansalud', models.CharField(max_length=100)),
                ('fechaplansalud', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appclinica.comuna')),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1, null=True)),
                ('fechanac', models.DateField(null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appclinica.cliente')),
            ],
            options={
                'db_table': 'mascota',
            },
        ),
        migrations.CreateModel(
            name='cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('observacion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appclinica.control')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appclinica.estadocita')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appclinica.mascota')),
            ],
            options={
                'db_table': 'cita',
            },
        ),
        migrations.CreateModel(
            name='atencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaatencion', models.DateTimeField(auto_now_add=True)),
                ('evolucion', models.TextField()),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appclinica.mascota')),
            ],
            options={
                'db_table': 'atencion',
            },
        ),
        migrations.CreateModel(
            name='atenciondetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('atencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appclinica.atencion')),
                ('prestacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appclinica.prestacion')),
            ],
            options={
                'db_table': 'atenciondetalle',
            },
        ),
        migrations.CreateModel(
            name='raza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appclinica.especie')),
            ],
            options={
                'db_table': 'raza',
            },
        ),
        migrations.AddField(
            model_name='mascota',
            name='raza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appclinica.raza'),
        ),
    ]
