# Generated by Django 5.2.9 on 2025-12-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appclinica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fechaplansalud',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='plansalud',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
