# Generated by Django 5.2.9 on 2025-12-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appclinica', '0002_alter_cliente_fechaplansalud_alter_cliente_plansalud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fechaplansalud',
            field=models.DateField(blank=True, null=True),
        ),
    ]
