# Generated by Django 5.2.9 on 2025-12-19 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appclinica', '0003_alter_cliente_fechaplansalud'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appclinica.estadocliente'),
        ),
    ]
