# Generated by Django 5.2.9 on 2025-12-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appclinica', '0004_cliente_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fechaterminoplan',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='especie',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='prestacion',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddConstraint(
            model_name='raza',
            constraint=models.UniqueConstraint(fields=('especie', 'nombre'), name='uq_raza_especie_nombre'),
        ),
    ]
