# Generated by Django 5.2.9 on 2025-12-23 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appclinica', '0005_cliente_fechaterminoplan_alter_especie_nombre_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comuna',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='control',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='especie',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='prestacion',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='raza',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterField(
            model_name='mascota',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Macho'), ('H', 'Hembra')], default='M', max_length=1, null=True),
        ),
    ]
