# Generated by Django 5.2.9 on 2025-12-26 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appclinica', '0006_alter_comuna_options_alter_control_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='chat_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
