# Generated by Django 5.2.9 on 2025-12-29 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appclinica', '0007_cliente_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='chat_id',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
