# Generated by Django 5.2.9 on 2026-01-07 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appclinica', '0008_alter_cliente_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencion',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
