# Generated by Django 5.2.9 on 2026-01-07 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appclinica', '0009_atencion_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='chip',
            field=models.IntegerField(null=True),
        ),
    ]
