# Generated by Django 5.2.9 on 2026-01-07 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appclinica', '0010_mascota_chip'),
    ]

    operations = [
        migrations.AddField(
            model_name='atenciondetalle',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
