# Generated by Django 5.2.9 on 2026-01-07 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appclinica', '0011_atenciondetalle_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='atenciondetalle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
