# Generated by Django 5.2.9 on 2026-01-08 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appclinica', '0012_alter_atencion_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='chip',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
