# Generated by Django 5.2.9 on 2026-01-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appclinica', '0013_alter_mascota_chip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='chip',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
