# Generated by Django 5.2.9 on 2026-01-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appclinica', '0014_alter_mascota_chip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='nombre',
            field=models.CharField(db_index=True, max_length=80),
        ),
    ]
