# Generated by Django 5.2.9 on 2026-03-31 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appclinica', '0015_alter_mascota_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='agendabloqueo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'agendabloqueo',
                'ordering': ['-fecha_inicio', 'hora_inicio', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='agendaevento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'agendaevento',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('email_contacto', models.EmailField(max_length=254)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], db_index=True, default='pendiente', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appclinica.agendaevento')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appclinica.mascota')),
            ],
            options={
                'db_table': 'reserva',
                'ordering': ['fecha', 'hora_inicio', 'mascota__nombre'],
            },
        ),
        migrations.CreateModel(
            name='agendaeventohorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miercoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sabado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('activo', models.BooleanField(default=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='appclinica.agendaevento')),
            ],
            options={
                'db_table': 'agendaeventohorario',
                'ordering': ['dia_semana', 'hora_inicio', 'hora_fin'],
                'constraints': [models.UniqueConstraint(fields=('evento', 'dia_semana', 'hora_inicio', 'hora_fin'), name='uq_agendaevento_slot')],
            },
        ),
    ]
