# Generated by Django 5.2.9 on 2026-04-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appclinica', '0016_agendabloqueo_agendaevento_reserva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='origen',
            field=models.CharField(choices=[('sistema', 'Sistema'), ('web', 'Web')], default='sistema', max_length=20),
        ),
    ]
