# Generated by Django 5.2.9 on 2026-06-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appclinica', '0017_cliente_origen'),
    ]

    operations = [
        migrations.CreateModel(
            name='promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('texto_correo', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'promocion',
                'ordering': ['-fecha_creacion', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='veterinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('logo', models.URLField(blank=True, null=True)),
                ('correo', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'veterinaria',
                'ordering': ['nombre'],
            },
        ),
    ]
