# Generated by Django 5.2.9 on 2026-06-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appclinica', '0018_promocion_veterinaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinaria',
            name='smtp_host',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='veterinaria',
            name='smtp_password',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='veterinaria',
            name='smtp_port',
            field=models.PositiveIntegerField(default=587),
        ),
        migrations.AddField(
            model_name='veterinaria',
            name='smtp_usa_ssl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='veterinaria',
            name='smtp_usa_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='veterinaria',
            name='smtp_usuario',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
