# Generated by Django 5.2.9 on 2026-06-02 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appclinica', '0020_crea_rol_administrador'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinaria',
            name='correo_prueba',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
